name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build-test:
    name: Build and Test (Zig ${{ matrix.zig-version }})
    strategy:
      fail-fast: false
      matrix:
        # Use macos-13 (Intel/x86_64) for consistent artifact availability.
        os: [ ubuntu-latest, macos-13, windows-latest ]
        zig-version: [ 0.15.2 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zig (Windows) ${{ matrix.zig-version }}
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $Version = '${{ matrix.zig-version }}'
          $Url = "https://ziglang.org/download/$Version/zig-windows-x86_64-$Version.zip"
          Write-Host "Downloading $Url"
          $Zip = "$env:RUNNER_TEMP\zig.zip"
          Invoke-WebRequest -Uri $Url -OutFile $Zip
          $Extract = "$env:RUNNER_TEMP\zig"
          Expand-Archive -Path $Zip -DestinationPath $Extract -Force
          $ZigPath = Join-Path $Extract "zig-windows-x86_64-$Version"
          echo $ZigPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          & "$ZigPath\zig.exe" version

      - name: Install Zig (Linux/macOS) ${{ matrix.zig-version }}
        if: runner.os != 'Windows'
        shell: bash
        run: |
          set -euxo pipefail
          VERSION='${{ matrix.zig-version }}'
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            PLATFORM=linux
            ARCH=x86_64
            EXT=tar.xz
          else
            PLATFORM=macos
            ARCH=x86_64
            EXT=tar.xz
          fi
          URL="https://ziglang.org/download/${VERSION}/zig-${PLATFORM}-${ARCH}-${VERSION}.${EXT}"
          echo "Downloading $URL"
          TMPDIR="${RUNNER_TEMP}/zigdl"
          mkdir -p "$TMPDIR"
          curl -fsSL "$URL" -o "$TMPDIR/zig.${EXT}"
          tar -xJf "$TMPDIR/zig.${EXT}" -C "$RUNNER_TEMP"
          ZIGDIR="$RUNNER_TEMP/zig-${PLATFORM}-${ARCH}-${VERSION}"
          echo "$ZIGDIR" >> "$GITHUB_PATH"
          "$ZIGDIR/zig" version

      - name: Show Zig version
        run: zig version

      - name: Format check
        run: zig fmt --check .

      - name: Build
        run: zig build

      - name: Run tests
        run: zig build test

      - name: Smoke run (help)
        run: zig build run || true
