name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build-test:
    name: Build and Test (Zig 0.15.x)
    strategy:
      fail-fast: false
      matrix:
        # Use macos-13 (Intel/x86_64) to ensure Zig 0.15.0 artifact availability
        os: [ ubuntu-latest, macos-13, windows-latest ]
        zig-version: [ 0.15.0 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zig ${{ matrix.zig-version }}
        id: setup-zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Fallback install latest Zig (only if specific version unavailable)
        if: failure()
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: latest

      - name: Show Zig version
        run: zig version

      - name: Format check
        run: zig fmt --check .

      - name: Build
        run: zig build

      - name: Run tests
        run: zig build test

      - name: Smoke run (help)
        run: zig build run || true
